const adsData = [
    {
        id: 1,
        title: "iPhone 13 128 gb",
        price: "35 000 ₽",
        image: "images/iPhone13.png",
        description: "Отличное состояние, 95% батареи. В комплекте оригинальная коробка и кабель.",
    },
    {
        id: 2,
        title: "Толстовка",
        price: "2 500 ₽",
        image: "images/hoodie.png",
        description: "Хлопковая толстовка унисекс, новая с бирками. Размер M.",
    },
    {
        id: 3,
        title: "Механические часы",
        price: "8 900 ₽",
        image: "images/watch.png",
        description: "Японский механизм, кожаный ремешок. Полная комплектация.",
    },
    {
        id: 4,
        title: "Деревянная птичка ручной работы",
        price: "1 200 ₽",
        image: "images/wooden_bird.png",
        description: "Декоративная фигурка из массива дуба. Идеально для интерьера.",
    },
    {
        id: 5,
        title: "Тумба для ТВ из массива сосны",
        price: "12 500 ₽",
        image: "images/tv_stand.png",
        description: "Экологичная мебель с двумя полками. Габариты 120x40x50 см.",
    },
    {
        id: 6,
        title: "Утка на велосипед",
        price: "890 ₽",
        image: "images/bike_duck.png",
        description: "Веселый аксессуар для руля велосипеда.",
    },
    {
        id: 7,
        title: "Ремешок для Apple Watch",
        price: "3 200 ₽",
        image: "images/watch_strap.png",
        description: "Оригинальный ремешок.",
    },
    {
        id: 8,
        title: "Свеча 'Popcorn' со вкусом попкорна",
        price: "950 ₽",
        image: "images/popcorn_candle.png",
        description: "Ароматическая свеча из соевого воска. Горение 35 часов.",
    },
    {
        id: 9,
        title: "Чехол для AirPods",
        price: "1 500 ₽",
        image: "images/airpods_case.png",
        description: "Силиконовый чехол сиреневого цвета. 100% защита от пыли.",
    },
    {
        id: 10,
        title: "Футболка",
        price: "1 800 ₽",
        image: "images/tshirt.png",
        description: "Классическая черная футболка из органического хлопка. Размер L.",
    },
    {
        id: 11,
        title: "Игровая приставка PS5",
        price: "52 000 ₽",
        image: "images/ps5.jpg",
        description: "Комплект с игрой Spider-Man 2. Гарантия до 2026 года.",
    },
    {
        id: 12,
        title: "Велосипед горный",
        price: "150 000 ₽",
        image: "images/mountain_bike.jpg",
        description: "Двухподвес с хорошим ходом вилки. Новый.",
    }
];